---


 - name: Oracle software installation
   hosts: "{{ oracle-install }}"
   remote_user: root
   roles:
      - ora-install

 - name: Oracle master node configuration
   hosts: "{{ ora-master }}"
   remote_user: root
   roles:
      - ora-master

 - name: Oracle slave node configuration
   hosts: "{{ ora-slave }}"
   remote_user: root
   roles:
      - ora-slave
