---
#
# Author: Jakit
# Date: 2019/05/08
#

- name: Oracle render initpri
  template: src=initpri.ora.j2 dest=/tmp/initpri.ora

- name: Oracle render listener
  template: src=listener.ora.j2 dest=/tmp/listener.ora

- name: Oracle render tnsnames
  template: src=tnsnames.ora.j2 dest=/tmp/tnsnames.ora

- name: Oracle master with Redhat copy script
  copy:
    src: prepare_database.sh
    dest: /tmp
    mode: 0755

- name: Oracle Master Prepare Database
  shell: "/tmp/prepare_database.sh"
  ignore_errors: True
