---
#
# Author: Jakit
# Date: 2019/05/08
#

# Copying scripts

- name: Oracle dependences with Redhat copy script 1
  copy:
    src: prepare_redhat_repo.sh
    dest: /tmp
    mode: 0755

- name: Oracle dependences with Redhat copy script 2
  copy:
    src: change_host.sh
    dest: /tmp
    mode: 0755

- name: Oracle dependences with Redhat copy script 3
  copy:
    src: init.sh
    dest: /tmp
    mode: 0755

- name: Oracle dependences with Redhat copy script 4
  copy:
    src: exec_install.sh
    dest: /tmp
    mode: 0755

- name: Oracle dependences with Redhat copy script 5
  copy:
    src: install.sh
    dest: /tmp
    mode: 0755

- name: Oracle dependences with Redhat copy script 6
  copy:
    src: database_initialize.sh
    dest: /tmp
    mode: 0755

- name: Oracle dependences with Redhat copy script 7
  copy:
    src: delay.sh
    dest: /tmp
    mode: 0755

# Dependences

- name: Oracle dependences with Redhat copy rpm
  copy:
    src: pdksh-5.2.14-30.x86_64.rpm
    dest: /tmp
    mode: 0755

# Rendering

- name: Oracle env render
  template: src=env.txt.j2 dest=/tmp/env.txt

- name: Oracle host setting
  template: src=hosts.j2 dest=/tmp/hosts

- name: Oracle render config
  template: src=db_install.rsp.j2 dest=/tmp/db_install.rsp

# Execution

- name: Oracle dependences with Redhat install
  shell: "/tmp/prepare_redhat_repo.sh"
  ignore_errors: True

- name: Oracle host config
  shell: "/tmp/change_host.sh"
  ignore_errors: True

- name: Oracle initialize environment
  shell: "/tmp/init.sh"
  ignore_errors: True

- name: Oracle installation
  shell: "/tmp/exec_install.sh"
  ignore_errors: True

- name: Oracle installation wait finish 1
  shell: "/tmp/delay.sh"
  ignore_errors: True

- name: Oracle installation wait finish 2
  shell: "/tmp/delay.sh"
  ignore_errors: True

- name: Oracle installation wait finish 3
  shell: "/tmp/delay.sh"
  ignore_errors: True

- name: Oracle init database
  shell: "/tmp/database_initialize.sh"
  ignore_errors: True
