---
#
# Author: Jakit
# Date: 2019/05/08
#

- name: Oracle dependences with Redhat copy install script
  copy:
    src: prepare_redhat_repo.sh
    dest: /tmp
    mode: 0755

- name: Oracle dependences with Redhat install
  shell: "/tmp/prepare_redhat_repo.sh"

- name: Oracle host config
  shell: "/bin/bash {{ role_path }}/files/change_host.sh"

- name: Oracle copy config
  template: src=db_install.rsp.j2 dest=/tmp/db_install.rsp

- name: Oracle installation
  shell: "/bin/bash {{ role_path }}/files/install.sh"

- name: Oracle render dbca config
  template: src=dbca.rsp.j2 dest=/tmp/dbca.rsp

- name: Oracle init database
  shell: "/bin/bash {{ role_path }}/files/database_initialize.sh"
