---
#
# Author: Jakit
# Date: 2019/05/08
#

- name: Oracle render initpri
  template: src=initpri.ora.j2 dest=/tmp/initpri.ora

- name: Oracle render listener
  template: src=listener.ora.j2 dest=/tmp/listener.ora

- name: Oracle render tnsnames
  template: src=tnsnames.ora.j2 dest=/tmp/tnsnames.ora

- name: Oracle copy orapwstd
  copy: src=orapwstd dest=/tmp/orapwstd

- name: Oracle slave with Redhat copy script 1
  copy:
    src: prepare_slave_database.sh
    dest: /tmp
    mode: 0755

- name: Oracle slave with Redhat copy script 2
  copy:
    src: recover_slave_from_master.sh
    dest: /tmp
    mode: 0755

- name: Oracle slave node config
  shell: "/tmp/prepare_slave_database.sh"
  ignore_errors: True

- name: Oracle slave sync with master
  shell: "/tmp/recover_slave_from_master.sh"
  ignore_errors: True
